// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddProductForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex justify-center items-center m-auto gap-4\"><h2>Add a product</h2><form id=\"productForm\" action=\"/products\" method=\"POST\" enctype=\"multipart/form-data\" class=\"flex flex-col justify-center items-center gap-2 rounded-md border border-black\"><label for=\"name\">Name:</label> <input type=\"text\" id=\"name\" name=\"name\" required> <label for=\"description\">Description:</label> <textarea id=\"description\" name=\"description\" rows=\"4\" cols=\"50\" required></textarea> <label for=\"quantity\">Quantity:</label> <input type=\"number\" id=\"quantity\" name=\"quantity\" required> <label for=\"price\">Price:</label> <input type=\"number\" id=\"price\" name=\"price\" step=\"0.01\" required> <label for=\"category\">Category:</label> <input type=\"text\" id=\"category\" name=\"category\" required> <label for=\"image\">Image:</label> <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/*\" required> <input type=\"submit\" value=\"Submit Product\" class=\"bg-gray-300\"></form></div><script type=\"text/javascript\">\n    document.getElementById('productForm').addEventListener('submit', function(e) {\n        e.preventDefault();\n        \n        var formData = new FormData(this);\n        \n        fetch('/products', {\n            method: 'POST',\n            body: formData\n        })\n        .then(response => {\n            if (response.ok) {\n                alert('Product added successfully');\n                window.location.href = '/panel';\n            } else {\n                throw new Error('Product submission failed');\n            }\n        })\n        .catch(error => {\n            console.error('Error:', error);\n            alert('Error adding product');\n        });\n    });\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
