// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views_page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HowPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex-grow flex items-center justify-center py-16\"><div class=\"w-full max-w-screen-lg px-4\"><div class=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12\"><!-- Step 1 --><div class=\"border-4 border-white rounded-lg flex flex-col items-center justify-center gap-6 shadow-lg w-full max-w-xs p-6\"><img src=\"images/vape.png\" class=\"w-24 h-24 object-contain\" alt=\"Step 1\"><div class=\"text-center\"><h4 class=\"font-semibold capitalize text-3xl step-title text-white\">STEP 1</h4><p class=\"text-white text-lg mt-4\">WYBIERZ PRODUKT ODPOWIEDNI SMAK MOC ORAZ POJEMNOŚĆ NASTEPNIE DODAJ DO KOSZYKA</p></div></div><!-- Step 2 --><div class=\"border-4 border-white rounded-lg flex flex-col items-center justify-center gap-6 shadow-lg w-full max-w-xs p-6\"><img src=\"images/basket.png\" class=\"w-24 h-24 object-contain\" alt=\"Step 2\"><div class=\"text-center\"><h4 class=\"font-semibold capitalize text-3xl step-title text-white \">STEP 2</h4><p class=\"text-white text-lg mt-4\">PRZEJDŹ DO KOSZYKA. SFINALIZUJ ZAMÓWIENIE PODAJĄC ADRES PACZKOMATU ORAZ NICK Z APLIKACJI SIGNAL</p></div></div><!-- Step 3 --><div class=\"border-4 border-white rounded-lg flex flex-col items-center justify-center gap-6 shadow-lg w-full max-w-xs p-6\"><img src=\"images/chat.png\" class=\"w-24 h-24 object-contain\" alt=\"Step 3\"><div class=\"text-center\"><h4 class=\"font-semibold capitalize text-3xl step-title text-white\">STEP 3</h4><p class=\"text-white text-lg mt-4\">OCZEKUJ NA ULTRASZYBKĄ ODPOWIEDŹ NA APLIKACJI SIGNAL W CELU SFINALIZOWANIA ZAMÓWIENIA</p></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
